service: sls-upload-s3

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: go1.x
  memorySize: 512

  stage: dev
  region: sa-east-1


  httpApi:
    cors: true

  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - s3:PutObject
          Resource: 
            - ${env:ARN-BUCKET}

package:
  artifact: bin/function.zip

functions:
  upload:
    handler: bin/upload
    events:
      - httpApi:
          path: /sls/upload-s3
          method: post